title: <center>Keenan Sivitz</center> # your name (or website title) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
 <center><img src="/images/IMG_2643-modified.png?raw=true"/ width=75% height=75%> </center>
 <br>
 <center><a href="pdf/Resume-ML.pdf">Resume</a></center>
 <br>
  I am looking to start a career as a Data Scientist / Machine Learning Engineer. I have completed a comprehensive Udemy Masterclass as well as trained on several personal projects, and am looking for the opportunity to put my skills to good use!
  <br>
   
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
