title: <center>Keenan Sivitz</center> # your name (or website title) here 
description: > # your text below (remove <br> elements if you don't need line breaks)
 <center><img src="/images/IMG_2643-modified.png?raw=true"/ width=70% height=70%> </center>

 <center><a href="pdf/Keenan-Sivitz-Resume.pdf">Resume</a></center>
 <br><center>
  My name is Keenan Sivitz and I am looking to start a career as a Data Scientist / Machine Learning Engineer. I am a ceritiied AWS Machine Learning Specialist, have completed a comprehensive Udemy Masterclass, trained on several personal projects, and am looking for the opportunity to put my skills to use!
  </center><br>
   
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
