title: <center>Keenan Sivitz</center> # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

I have spent the last few years of my life at a loss. where am i going? what am I doing? Who am I? then i discovered data science and machine learning and now I am my best self. So vote for me for your job, you wont regret it!  <br><br>
  Lets do it! 
  <br><br>
   
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
